# Site settings
title: Timothy Cao
email: tctctc888@gmail.com
url: https://timothy-cao.github.io/
description: "Timothy Cao's Personal Website."
keywords: "Timothy Cao, Personal website, 2024"
skills: "Fullstack Developer - Technical Lead - Designer"
meta_author: Cao Timothy

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 818FB4 #18bc9c #
  primary-rgb: "54,48,98" #"128,179,255"
  secondary: 435585 #FD6E8A
  secondary-dark: 363062 #A2122F

# Footer settings
footer:
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: https://www.youtube.com/channel/UCNx2UtrexMU35fE8VfY_8Zw
  - title: tiktok
    url: https://monkeytype.com/profile/dodoman767
  - title: linkedin
    url: https://www.linkedin.com/in/timothyc767/
  - title: instagram
    url: https://www.instagram.com/timothy_cao/
  - title: github
    url: https://github.com/Timothy-Cao

# Postal address (add as many lines as necessary)
address:
  - line: Markham
  - line: Ontario, Canada

# Credits content
credits: 'Jekyll Themes used for UI/UX'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
